# frozen_string_literal: true

require "cgi"

module Jekyll
  module BibliographyFilters
    URL_PATTERN = %r{https?://[^\s<]+}.freeze
    TRAILING_PUNCTUATION = /[.,;:]+\z/.freeze
    HTML_TAG = /(<[^>]+>)/.freeze
    REFERENCE_NUMBER = /\A\[(\d+)\](?=\S)/.freeze

    # CiteProc emits URL fields as plain text. Process only text fragments so
    # future links or other HTML generated by a CSL style remain untouched.
    def linkify_bibliography(input)
      number_wrapped = false

      input.to_s.split(HTML_TAG).map do |fragment|
        next fragment if fragment.start_with?("<")

        unless number_wrapped
          fragment = fragment.sub(REFERENCE_NUMBER) do
            number_wrapped = true
            number = Regexp.last_match(1)
            %(<span class="reference-number" aria-hidden="true">[#{number}]</span><span class="sr-only">文献 #{number}：</span>)
          end
        end

        fragment.gsub(URL_PATTERN) do |raw_url|
          url = raw_url.sub(TRAILING_PUNCTUATION, "")
          punctuation = raw_url.delete_prefix(url)
          escaped_url = CGI.escapeHTML(CGI.unescapeHTML(url))

          %(<a class="reference-url" href="#{escaped_url}" target="_blank" rel="noopener noreferrer">#{escaped_url}</a>#{punctuation})
        end
      end.join
    end
  end
end

Liquid::Template.register_filter(Jekyll::BibliographyFilters)
